type: object
properties:
  listen: { type: string, format: ipv4 }

  port:
    anyOf:
      - { type: integer, format: ip-port }
      - { type: array, items: { type: integer, format: ip-port }, minItems: 1, uniqueItems: true }

  trustedSubnets:
    anyOf:
      - { type: ["null", boolean] }
      - { type: array, items: { type: string }, uniqueItems: true }

  default_zone: { type: ["null", string] }

  zones:
    type: object
    additionalProperties:
      type: object
      properties:
        proxy: { type: [string, object] }
      required: [proxy]
      additionalProperties: false

  whitelist:
    anyOf:
      - { type: ["null", string] }
      - { type: array, items: { type: string }, uniqueItems: true }

  users:
    type: object
    additionalProperties:
      type: object
      properties:
        enabled: { type: boolean }

        password: { type: string }

        whitelist:
          anyOf:
            - { const: false }
            - { type: ["null", string] }
            - { type: array, items: { type: string }, uniqueItems: true }

        default_zone:
          anyOf:
            - { const: false }
            - { type: ["null", string] }

        zones:
          anyOf:
            - { type: ["null", string] }
            - { type: array, items: { type: string }, minItems: 1, uniqueItems: true }

      required: [enabled, password, whitelist, default_zone, zones]
      additionalProperties: false

required: [listen, port, default_zone, zones, whitelist, users]
additionalProperties: false
