#!/usr/bin/env -S docker stack deploy --with-registry-auth proxy -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml proxy
# docker node update --label-add proxy=true <NODE-NAME>

services:
  proxy:
    image: ghcr.io/zerocluster/proxy
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      labels:
        # nginx.0: upstream=80&server=443&serverName=proxy.softvisio.net
        nginx.1: upstream=8085:proxy-protocol&server=8085,8085:ssl&serverName=proxy.softvisio.net

    command: run

    secrets:
      - { source: env.yaml, target: /var/local/package/env.yaml }

    networks: [main]

    # ports:
    #   - { published: 8085, target: 8085 }

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }

    build: .

secrets:
  env.yaml: { file: env.yaml }

networks:
  main: { external: true }
